export * from './HeroSiniestros'
export * from './SiniestroSteps'
export * from './SelectSiniestro'
export * from './SiniestroGM'
export * from './SiniestroAuto'
export * from "./MainSiniestroAuto";
export * from "./MainSiniestroGM";
export * from "./Step1SiniestroA";
export * from "./Step2SiniestroA";
export * from './Step3SiniestroA';
export * from './Step4SiniestroA';
export * from './FinalSiniestroPage';